name: CI/CD

on:
  push:
    branches: [ main ]
    

env:
    REACT_APP_apiKey = AIzaSyDhtbtp20_896ytKvuRmWXYKt0RhDqFJu0
    REACT_APP_authDomain= geeksforgeeks-42d5f.firebaseapp.com
    REACT_APP_projectId= geeksforgeeks-42d5f
    REACT_APP_storageBucket= geeksforgeeks-42d5f.appspot.com
    REACT_APP_messagingSenderId= 64227012466
    REACT_APP_appId= 1:64227012466:web:008f4026a26eecfb7877eb
    REACT_APP_measurementId = G-4L7F4T7QH9
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: 
            npm install
            npm run build
      - name: Firebase Deploy
        run: |
          sudo npm install -g firebase-tools
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN}}
